### ISSUE TITLE
Documentation: didn't expect the github authentication

### ISSUE THREAD

**Issue by khawkins98** [oss6/vf-core-service-discovery#22]
When executing `vf-core-service-discovery run` it prompts for the github auth. I wasn't expecting this and I'm not really sure why it's needed. 

Would be nice/good to:

- add an explainer to README.md
- add an explainer to the console prompt 

I'd be happy to raise a PR, but again I'm not really sure why the GitHub auth is needed.

**Comment by oss6** [comment]
The authentication is needed to get the latest version of vf-core (e.g. now
2.4.3). This will help getting the raw contents from github (e.g.
config.yml). Otherwise we have to use the develop branch which is not
representative of the latest released version. Do you think there's another
solution without having authentication?

Yes go ahead with a PR if it's clearer now!

**Comment by khawkins98** [comment]
Hrm, we have:

https://github.com/visual-framework/vf-core/blob/979b1256c82c318146794df8109939f322ae1f5c/tools/vf-component-library/src/site/_data/siteConfig.js#L18

```json
  vfVersion: "v2.4.4",
```

We could also/alternatively put the latest VF version on a URL like https://stable.visual-framework.dev/latest.json

Would that be helpful and remove the need for the github auth?

**Comment by oss6** [comment]
Yes absolutely, that'll be much better and won't need auth. I suppose the siteConfig.js vfVersion changes prerelease? In that case the second option would be great. But we can use siteConfig.js as well.

**Comment by khawkins98** [comment]
Coming back to this, how would making vf-core's pacakge.json file available work?

Url would be like `stable.visual-framework.dev/assets/vf-core/package.json`

Contents:

```json
{
  "name": "@visual-framework/vf-core",
  "version": "2.2.14",
  "description": "Common dependencies for the Visual Framework 2.0.",
  "main": "index.js",
  "vfConfig": {
...
```

So then you could just pull in the latest version from this file, sound good/ideal?

**Comment by oss6** [comment]
Yes that is ideal! I can even get it from the npm registry (forgot about the `vf-core` package!). I'll go ahead and remove authentication. Hopefully by tomorrow a release with the fixes and a test run against all components in `vf-core` will be available :+1:
Thanks!

**Comment by khawkins98** [comment]
Ok, great. I'll assume that you can get it from the register — if for some reason that causes an issue, just let me know and we can also deploy the package.json as a static asset.

**Comment by oss6** [comment]
Hi! Sorry I didn't work on it this week, was very busy.
I have a question, what's the difference between the version in the GitHub tags/releases (e.g. `2.4.5`) and the version from https://www.npmjs.com/package/@visual-framework/vf-core (`2.2.16`)? Basically I need the tag version to access to access the files from GitHub. Otherwise I'll need to download the repository, however I'm trying to limit the things saved on the user's machine (apart from cached files and logs).

**Comment by khawkins98** [comment]
- The tagged release is the "overall" project that we use to create the release for the CDN at https://assets.emblstatic.net/vf/v2.4.5/css/styles.css
- And the npm release of vf-core is for the build process of the CSS, JS and some other things (this will eventually go away as code is moved into some other packages). 

There's a little about this at https://github.com/visual-framework/vf-core/blob/develop/PUBLISHING.md#4-post-release

Which version do you need to discover? The one for https://www.npmjs.com/package/@visual-framework/vf-core ? If so could you use https://unpkg.com/@visual-framework/vf-core@2.2.16/package.json ?

**Comment by khawkins98** [comment]
Or for the github project: https://api.github.com/repos/visual-framework/vf-core/releases/latest

**Comment by oss6** [comment]
The GitHub project link is perfect! Allows getting the `tag_name`. Thanks again 👍

**Comment by khawkins98** [comment]
Cheers. thanks for the work on this project. Looking forward to testing the new release next week.
